project_name: LMU
pkg_name: lmu
repo_name: nengo/lmu
description: LMU metapackage for installing various LMU implementations

copyright_start: 2020
license: abr-free
main_branch: main

license_rst: {}

manifest_in: {}

setup_py:
  python_requires: ">=3.6"
  url: https://github.com/nengo/lmu
  install_req:
    # minimum version specified because we import it in __init__
    - keras-lmu>=0.4.0
  tests_req:
    - pytest>=6.1.0
  classifiers:
    - "Development Status :: 3 - Alpha"
    - "Intended Audience :: Science/Research"
    - "Operating System :: OS Independent"
    - "Programming Language :: Python "
    - "Programming Language :: Python :: 3.6"
    - "Programming Language :: Python :: 3.7"
    - "Programming Language :: Python :: 3.8"
    - "Topic :: Scientific/Engineering "
    - "Topic :: Scientific/Engineering :: Artificial Intelligence"

ci_scripts:
  - template: test
  - template: deploy
    wheel: true

pre_commit_config_yaml: {}

pyproject_toml: {}

version_py:
  major: 0
  minor: 4
  patch: 1
  release: false
